### ISSUE TITLE
Talk/Vortrag  6. November 2024

### ISSUE THREAD

**Issue by alfirak** [nika-d/svelte-berlin#12]
Ilja Sperling erzählt über Svelte mit Astro als SvelteKit-Alternative.

Please dont forget to provide data for your talk announcement. :) -> See [FAQ-speakers-Vortragende.md](https://github.com/nika-d/svelte-berlin/blob/main/FAQ-speakers-Vortragende.md) 

Bitte nicht vergessen, die Infos für die Vortragsankündigung anzugeben. :) -> Siehe [FAQ-speakers-Vortragende.md](https://github.com/nika-d/svelte-berlin/blob/main/FAQ-speakers-Vortragende.md)

**Comment by alfirak** [comment]
Lieber Ilja, kannst du bitte dein Vortrag kurz auf Deutsch und auf Englisch beschreiben? 

Und scheibe bitte an welchem Tag im Oktober du Zeit hast, deinen Vortrag zu halten? 
Es muss irgendein Mittwoch um 18:30 Uhr sein.

**Comment by nika-d** [comment]
Also es geht nur um Mittwoche. Wir haben noch keinen festen Termin, aber am besten wäre 9.10. oder 16.10. .

**Comment by nika-d** [comment]
Ilja has a long timeslot for his talk.

In the october meeting, there is still time for a short impulse 10-15 minutes.

**Comment by fubits1** [comment]
@nika-d @alfirak - finally managed to write the teaser. I guess we might want to stick to "English first":

Speaker: Ilja | fubits 

Astro & Svelte - best of both worlds

Astro is a fully featured (meta) framework with a focus on content: handling markup and images probably can't get easier than this. To add interaction, their "islands architecture" approach allows for integrating (and even mixing) popular frontend frameworks such as Svelte.

In this live-coding session, Ilja will show us how to get the most out of Astro's and Svelte's respective perks and how this approach ranks against using SvelteKit.

Ilja is a Berlin-based freelance and currently works at the Tagesspiegel Innovation Lab.

**Comment by alfirak** [comment]
Hello dear participants of the Svelte CoP,

We hope you're all doing well! Unfortunately, we have to move our planned meeting by one month. We apologize for the late notice and any inconvenience this may cause, and we hope the new date works for everyone.

Thank you for your understanding, and we look forward to seeing you next week!

Best regards,
Alfira and Nika

**Comment by nika-d** [comment]
@flo-bit bitte deine Slides noch hier reinverlinken: https://github.com/nika-d/svelte-berlin . kannst die slides auch gerne hier irgendwo ins repo hochladen, falls das für dich praktisch ist, oder halt nen eternen link, wie du magst. :)

**Comment by nika-d** [comment]
@fubits1 bitte deine Slides noch hier reinverlinken: https://github.com/nika-d/svelte-berlin . kannst die slides auch gerne hier irgendwo ins repo hochladen, falls das für dich praktisch ist, oder halt nen eternen link, wie du magst. :)
