### ISSUE TITLE
Talk/Vortrag 13. November 2024

### ISSUE THREAD

**Issue by nika-d** [nika-d/svelte-berlin#14]
Please dont forget to provide data for your talk announcement. :) -> See [FAQ-speakers-Vortragende.md](https://github.com/nika-d/svelte-berlin/blob/main/FAQ-speakers-Vortragende.md) 

Bitte nicht vergessen, die Infos für die Vortragsankündigung anzugeben. :) -> Siehe [FAQ-speakers-Vortragende.md](https://github.com/nika-d/svelte-berlin/blob/main/FAQ-speakers-Vortragende.md)

**Comment by flo-bit** [comment]
I'd like to talk about [threlte](https://github.com/threlte/threlte) probably for around 30-40 minutes (and I would probably default to english).

**Name**: Florian Killius
**Titel**: 3D in the browser with threlte.
**Teaser**: How to built awesome 3D experiences with WebGPU and WebGL using threlte, the state-driven three.js wrapper for svelte.

**Comment by nika-d** [comment]
cool @flo-bit , the slot is yours! 

@ others: there is still time left for another talk :)
