### ISSUE TITLE
Vortrag für 11.9.2024

### ISSUE THREAD

**Issue by nika-d** [nika-d/svelte-berlin#5]
Generell wollen wir keine Raketenwissenschaft draus machen, sondern einen Stammtisch von Nerds für Nerds. Daher stellen wir an die Vorträge auch keine hohen Anforderungen. Ein Impulsvortrag von 10Minuten reicht völlig, um eine Diskussion zu starten, bei der das Publikum ja auch aktiv teilnehmen soll. Moderation können wir abwechselnd oder gemeinsam übernehmen - es geht ja einfach darum, die Diskussion anzuregen, hier ist also kein Svelte-Tiefenwissen notwendig. Es ist aber auch möglich, z.B. einen detaillierten 40-minütigen Vortrag zu halten, wie die Vortragenden möchten, stage is yours.

**Comment by nika-d** [comment]
Schonmal recherchiert, wie Rich Harris zu erreichen wäre. Eigentlich gar nicht. :/ 
Mensch kanns hierüber probieren: 
https://x.com/Rich_Harris 
https://social.massalabs.com/@sean (Kollege von Rich bei Vercel)
Wahrscheinlich macht es explizit **keinen** Sinn, über Vercel zu gehen, vermute, die würden Geld dafür haben wollen.

**Comment by mischka1981** [comment]
Ich bin gespannt!

**Comment by nika-d** [comment]
matthias stahl spiegel anfragen...

**Comment by msigwart** [comment]
A colleague of mine (Antonio Sarcevic) would be interested in giving a talk on SvelteKit accessibility. 

Not sure if you already set a date for the meetup in September. If not, his preference would be calendar week 37/38 since he's not based in Berlin but will be around during that time.

**Comment by nika-d** [comment]
Great, thanks for the idea! :) I’m mostly off the grid until 24th Aug, but will try to arrange the next svelte cop date to fit Antonio’s schedule. Best wishes! Am 08.08.2024 um 20:34 schrieb Marten Sigwart ***@***.***>:﻿
A colleague of mine (Antonio Sarcevic) would be interested in giving a talk on SvelteKit accessibility.
Not sure if you already set a date for the meetup in September. If not, his preference would be calendar week 37/38 since he's not based in Berlin but will be around during that time.

**Comment by alfirak** [comment]
Hi Marten, here is the link for our next event on 11 September at 18:00: https://lu.ma/b1b8o33e 
Could you please share it with Antonio?

**Comment by nika-d** [comment]
Hi Anne :) 
Wie siehts denn bei euch aus, möchte vielleicht jemand von DevSuit auch einen Vortrag nächste Woche halten?

**Comment by nika-d** [comment]
kleiner test zu meinen mail notifications

**Comment by FabianClemenz** [comment]
Hi @nika-d @annebardtke 

(i think it's better to communicate in english here in general)
I would like to give a talk

**Comment by nika-d** [comment]
Ok great, happy to welcome you as speaker for tomorroe @FabianClemenz! I will finalize the luma meeting now.

**Comment by FabianClemenz** [comment]
@nika-d do you already have a timetable?

**Comment by nika-d** [comment]
hello @FabianClemenz no timetable. first come first speak. ;) second talk should start latest at 19:30.

**Comment by FabianClemenz** [comment]
@nika-d alright - should the talks be in english or german today?

**Comment by FabianClemenz** [comment]
@nika-d here are my slides :) https://drive.google.com/file/d/1MuNcPRAphfLTLCjdAZEHBIPijUmZTLAE/view?usp=share_link

**Comment by nika-d** [comment]
Hello @msigwart @FabianClemenz :) plz see #13 . And Marten, maybe you can let Antonio know? I dont have hin here on Github...
